# https://github.com/knojector/SteamAuthenticationBundle for configuration documentation
knojector_steam_authentication:
    login_success_redirect: 'app_home'
    login_failure_redirect: 'app_login'
